title: Intro to ArcGIS Pro
remote_theme: ubc-library-rc/rc-workshop-template
search_enabled: false
github_repo_url: "https://github.com/fiddleHeads/intro-to-arcgis-pro/"

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"
